### ISSUE TITLE
CORS Blocks OpenWeatherMap

### ISSUE THREAD

**Issue by J3RN** [jakke-korpelainen/newtab#18]
The following error is happening on my local machine (Mac OS X 10.10.2, Firefox 36.0.1)
![screen shot 2015-03-14 at 3 08 37 pm](https://cloud.githubusercontent.com/assets/2058614/6653130/38d4df88-ca5c-11e4-928c-f0f76b54840c.png)

**Comment by jakke-korpelainen** [comment]
I think this is related to hosting/firewall settings

**Comment by J3RN** [comment]
It's weird, because it's only sometimes. I'll keep looking into this and let you know.
