### ISSUE TITLE
Chinese Translation not showing properly. 

### ISSUE THREAD

**Issue by kevinjcliao** [jakke-korpelainen/newtab#19]
Hi, 
I'm currently trying to translate NewTab into Chinese (simplified and traditional). I've edited the time.lang.json file, and properly declared the locale in app.js. Unfortunately none of the strings I've translated are showing up. The locale should be appropriately declared as moment.js is showing the right day of week. 
![screen shot 2015-03-15 at 9 10 21 am](https://butt.githubusercontent.com/assets/8745371/6656116/404042fc-caf3-11e4-8e91-a2659991af4b.png)
Am I missing a step or configuration somewhere? My code is on: https://github.com/kevinjcliao/newtab/blob/master/languages/zh-TW/time.lang.json

**Comment by jakke-korpelainen** [comment]
![tw](https://cloud.githubusercontent.com/assets/3626319/6662366/8912f274-cbc3-11e4-8ab1-a71af662eb20.png)

Got it working and added the translations to master (thanks!). You'll need to change your user.json locale to zh-TW and then it should work as I added the support for zh-TW into app.js

https://github.com/jakke-korpelainen/newtab/commit/93e60f4195628e4b109b93e8176f651c223cffa5

**Comment by jakke-korpelainen** [comment]
Btw because you had that plugin which changes all the IT-buzzwords into something more fun, the link you gave had replaced cloud to butt into the post :smiley:
