### ISSUE TITLE
Doesn't clean out address bar

### ISSUE THREAD

**Issue by haf** [jakke-korpelainen/newtab#8]
When using your github.io page, it first gets cleared, then the page loads, then the address bar gets the URL of the page (incorrectly when the checkbox in the settings for a clean address bar, is checked).

**Comment by jakke-korpelainen** [comment]
I'll have a look that if the html5Mode would fix it. 

Meanwhile be sure to link it to 
jakke-korpelainen.github.io/newtab/#/
instead of 
jakke-korpelainen.github.io/newtab/ 

as the routing redirects it to /# hence changing the url.
